In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr + 2)
print(arr * 3)
print(arr / 2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])

[5 4 6 3 2 1]


In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value:", most_frequent)
print("Indices:", np.where(x == most_frequent)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [5]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value:", most_frequent)
print("Indices:", np.where(y == most_frequent)[0])

Most frequent value: 1
Indices: [0 1 2]


In [6]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0, 1])
print(arr[2, 0])

20
70


In [7]:
Arnav = np.linspace(10, 100, 25)

print("Dimensions:", Arnav.ndim)
print("Shape:", Arnav.shape)
print("Total elements:", Arnav.size)
print("Data type:", Arnav.dtype)
print("Total bytes:", Arnav.nbytes)

transpose_Arnav = Arnav.reshape(1, 25).T
print(transpose_Arnav)

print(Arnav.T)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [8]:
ucs420_Arnav = np.array([[10, 20, 30, 40],
                        [50, 60, 70, 80],
                        [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_Arnav))
print("Median:", np.median(ucs420_Arnav))
print("Max:", np.max(ucs420_Arnav))
print("Min:", np.min(ucs420_Arnav))
print("Unique elements:", np.unique(ucs420_Arnav))

reshaped_ucs420_Arnav = ucs420_Arnav.reshape(4, 3)
print(reshaped_ucs420_Arnav)

resized_ucs420_Arnav = np.resize(ucs420_Arnav, (2, 3))
print(resized_ucs420_Arnav)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
